# Generated by Django 4.2.1 on 2025-07-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_field', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraFieldModel',
        ),
    ]
